# Generated by Django 2.2.2 on 2019-07-19 15:42

from django.db import migrations

def init_categories(apps, schema_editor):
	Category = apps.get_model('streamer', 'Category')
	categories = [
		('Music', 'music'),
		('Entertainment', 'entertainment'),
		('Sports', 'sports'),
		('Film & Animation', 'film_animation'),
		('News & Politics', 'news_politics'),
		('Comedy', 'comedy'),
		('People & Blogs', 'people_blogs'),
		('Science & Technology', 'science_technology'),
		('Gaming', 'gaming'),
		('Howto & Style', 'howto_style'),
		('Education', 'education'),
		('Pets & Animals', 'pets_animals'),
		('Auto & Vehicles', 'auto_vehicles'),
		('Travel & Events', 'travel_events'),
		('Nonprofits & Activism', 'nonprofits_activism'),
	]
	for cat in categories:
		Category.objects.create(title=cat[0], name=cat[1])

class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0001_initial'),
    ]

    operations = [
    	migrations.RunPython(init_categories),
    ]
