# Generated by Django 2.2.2 on 2019-07-19 15:42

import random
import string

from django.db import migrations
from django.contrib.auth.hashers import make_password


def init_users(apps, schema_editor):
	User = apps.get_model('auth', 'User')
	Channel = apps.get_model('streamer', 'Channel')
	Profile = apps.get_model('streamer', 'Profile')
	data = [
		('john', 'John'),
		('bob', 'Bob'),
		('vidhub', 'Offical Vidhub'),
	]

	for username, channelname in data:
		user = User.objects.create(username=username, password=make_password('sommer', None, 'md5'))
		Profile.objects.create(user=user)
		channel = Channel.objects.create(name=channelname, owner=user)
		if not channel.channel_id:
			new_channel_id = generate_id(8)
			while Channel.objects.filter(channel_id=new_channel_id).exists():
				new_channel_id = generate_id(8)
			channel.channel_id = new_channel_id
		channel.save()

def generate_id(length):
	chars = string.ascii_letters + string.digits
	return ''.join(random.choice(chars) for _ in range(length))

class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0002_vidhub_init_categories'),
    ]

    operations = [
    	migrations.RunPython(init_users),
    ]
